AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway HTTP API with VPC Link to internal NLB listeners

Parameters:
  NetworkStackName:
    Type: String
  ApiName:
    Type: String
    Default: invoice-api

Resources:
  VpcLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: !Sub ${ApiName}-vpc-link
      SubnetIds: !Split [",", { 'Fn::ImportValue': !Sub '${NetworkStackName}:PublicSubnets' } ]
      SecurityGroupIds:
        - { 'Fn::ImportValue': !Sub '${NetworkStackName}:EcsSecurityGroupId' }

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiName
      ProtocolType: HTTP

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: $default
      AutoDeploy: true

  IntAdmin:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: HTTP_PROXY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref VpcLink
      IntegrationMethod: ANY
      IntegrationUri: { 'Fn::ImportValue': !Sub '${NetworkStackName}:ListenerArn8081' }

  IntInvoice:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: HTTP_PROXY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref VpcLink
      IntegrationMethod: ANY
      IntegrationUri: { 'Fn::ImportValue': !Sub '${NetworkStackName}:ListenerArn8082' }

  IntMailing:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: HTTP_PROXY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref VpcLink
      IntegrationMethod: ANY
      IntegrationUri: { 'Fn::ImportValue': !Sub '${NetworkStackName}:ListenerArn8083' }

  RouteAdmin:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'ANY /api/v1/{proxy+}'
      Target: !Sub integrations/${IntAdmin}

  RouteInvoice:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'ANY /api/invoice/v1/{proxy+}'
      Target: !Sub integrations/${IntInvoice}

  RouteMailing:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'ANY /api/mail/v1/{proxy+}'
      Target: !Sub integrations/${IntMailing}

Outputs:
  ApiId:
    Value: !Ref HttpApi
    Export:
      Name: !Sub "${AWS::StackName}:ApiId"
  ApiEndpoint:
    Value: !Sub https://$${HttpApi}.execute-api.$${AWS::Region}.amazonaws.com
    Export:
      Name: !Sub "${AWS::StackName}:ApiEndpoint"

