server:
  port: 8082
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: invoice-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  admin-base-url: ${ADMIN_BASE_URL}
  seed:
    user:
      email: ${SEED_USER_EMAIL}
      password: ${SEED_USER_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}

